apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-app

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: nginx-deployment
    count: 5

patches:
  - path: deployment-patch.yaml

images:
  - name: nginx
    newTag: 1.25-alpine
