apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-app

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/managed-by: kustomize

images:
  - name: nginx
    newTag: 1.25-alpine
